## Singular Value Decomposition (SVD)

As on slides, SVD of matrix A is:

A = UDV^T

Where:

• U is an orthogonal m X m matrix; its columns are the left-singular vectors of A.

• V is an orthogonal n x n matrix; its columns are the right-singular vectors of A.

• D is a diagonal m X n matrix; elements along its diagonal are the singular values of A.

In [5]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
A=np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [7]:
U,d,VT=np.linalg.svd(A)#V is already transposed

In [9]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [11]:
d

array([8.66918448, 4.10429538])

In [13]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [23]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

D must have the same dimension as for UDV^T matrix multiplication to be possible

In [32]:
D=np.concatenate((np.diag(d),[[0,0]]),axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [35]:
np.dot(U,np.dot(D,VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

SVD and eigendecomposition are closely related to each other:

Left-singular vectors of A = eigenvectors of A * A ^ T

Right-singular vectors of A = eigenvectors of A ^ T * A

• Non-zero singular values of A = square roots of eigenvectors of A * A ^ T = square roots of eigenvectors of A ^ T * A

Exercise: Using the matrix from the preceding PyTorch exercises, demonstrate that these three SVD-eigendecomposition equations are true.